
defaults
auth on
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt

account gmail
host smtp.gmail.com
port 587
from imadtaibi573@gmail.com
user imadtaibi573@gmail.com
password fmatiwiivriuktfw

account default : gmail
